### ISSUE TITLE
Hacer mas entendible al menos el resumen inicial

### ISSUE THREAD

**Issue by rusosnith** [gcba/Identidad-digital#1]
Si la idea es "resolver la problemática de la confianza en el mundo digital" al menos el resumen introductorio de este whitepaper debería estar dirigido a un público en general, sin usar palabras demasiado de nicho y al menos proponiendo ejemplos tangibles de que se lograría con esto.

**Comment by rusosnith** [comment]
Algo básico como plantear:
1. cuales son los problemas actuales
2. como esto propone solucionarlo

Algo en linea con este tipo de presentacion:
https://twitter.com/lucasjolias/status/1508927513916940291

**Comment by mkunik** [comment]
Gracias por tus comentarios. El proceso de co-creación de un Whitepaper es hacer legible el documento. Te invitamos a ayudarnos a co-crear en los diferentes capítulos del Whitepaper con tus aportes.

**Comment by dtrejopizzo** [comment]
Esta semana esperamos actualizar el whitepaper con casos de uso y una mejor explicación introductoria del whitepaper.

**Comment by dtrejopizzo** [comment]
@rusosnith Actualizados el punto 1 (resumen) y los puntos 2.1 y 2.2 con casos de uso. Por favor miralos y decinos que opinas, gracias!

**Comment by rusosnith** [comment]
Buenas, ahi le di una leida, creo que hay que repensar un poco como se plantea desde origen este tipo de documentos.
¿Cuál es el lector objetivo?
Yo diría que es un lector escéptico, que no confía en el estado, que no entiende bien quien está haciendo esto (decir que es una cocreacion cuando hay solo 4 contribuyendo es medio flojo) y que desde el vamos no entiende por que esto es necesario.

Explicar todo con "el futuro es blockchain" sin dar ningún fundamento está en las antípodas de querer generar justamente confianza. 

"utilizando blockchain como principal exponente de la tecnología descentralizada, que pone a la persona en el centro y al mando de su información"

Como entiendo esto siendo un ciudadano común? Tengo que confiar en quien me lo dice? Como estoy yo como ciudadano que no sabe ni lo que es blockchain ni le interesa, "al mando de mi información"?

Si el plan es salir del micronicho crypto y generar confianza en la sociedad (con lo cual concuerdo y celebro) debería plantearse el discurso de esa manera.

**Comment by emmavi** [comment]
> 
Es verdad lo que decís, al menos en parte, pero el ciudadano común no va a entrar github a ver un documento, creo que este es uno más técnico de lo que expresas y de lo que decís en tu tweet de referencia, quizás son dos documentos, primero este, donde están todos los tecnicismo y luego uno más bajado a lo terrenal una vez que se "resuelven" lo desafios técnicos.
