### ISSUE TITLE
Agregar opción de Mediator en Nivel 2

### ISSUE THREAD

**Issue by rodolfomiranda** [gcba/Identidad-digital#10]
A desarrollar:  [Aries RFC 0211: Mediator Coordination Protocol](https://github.com/hyperledger/aries-rfcs/blob/main/features/0211-route-coordination/README.md) (para que tengan en cuenta, varios de estos protocolos de Aries se van a adaptar y pasar a ser parte de DIF)

**Comment by dtrejopizzo** [comment]
Incorporado.
