### ISSUE TITLE
Verifiable Data Registry para VC

### ISSUE THREAD

**Issue by rodolfomiranda** [gcba/Identidad-digital#13]
El nivel 1 de ToIP es el VDR donde quedan anclados los DID desde donde se van a validar las claves públicas. Pero también es el lugar donde se puede validar otros temas como son los relacionados a credenciales. En particular se suele usar para:
- Guardar los esquemas de las credenciales: esto lo usa Indy (sobrin)y KILT entre otras. No lo veo tan necesario o crítico.
- Guardar las revocaciones a las credenciales: **esto es muy importante tenerlo**.

**Comment by dtrejopizzo** [comment]
Incorporado.
