### ISSUE TITLE
Listado de soluciones cerradas/comerciales

### ISSUE THREAD

**Issue by rodolfomiranda** [gcba/Identidad-digital#14]
Abro este issue para listar soluciones cerradas o comerciales. No estoy seguro si deban o no figurar en el documento, pero si creo importante saber que existen al menos. Aca listo algunas para empezar.

- [Cheqd](https://www.cheqd.io)
- [Evernym](https://www.evernym.com)
- [Sovrin](https://sovrin.org)
- [KILT](https://www.kilt.io)
- [Veramo](https://veramo.io)
- [Serto](https://www.serto.id)
- [ProofSpace](https://www.proofspace.id)

**Comment by dtrejopizzo** [comment]
Buenísimo, agregamos!
