### ISSUE TITLE
Nombre ¿identidad AUTO soberana?

### ISSUE THREAD

**Issue by pol82** [gcba/Identidad-digital#16]
Creo que el término AUTO está implicito en la Soberanía de nuestra identidad.
Un error de semántica podría restarle la seriedad que tiene el proyecto. 
La soberanía es el ejercicio de la autoridad sobre nuestra información privada y la autogestión es una de tantas facultades que nos otorga la soberanía. 
Recomiendo revisar y profundizar un poco más la semántica y el uso de palabras que pudieran atentar contra el real espíritu de la iniciativa.

**Comment by dtrejopizzo** [comment]
El nombre de Identidad Auto-Soberana se deriva de la traducción de varios trabajos que en Inglés se denominan **Self-Sovereign Identity (SSI)**. El objeto es que los titulares de la identidad individual crean y controlan completamente sus [credenciales verificables](https://didi.org.ar/aidi-identidad-digital-auto-soberana/#:~:text=Las%20credenciales%20verificables%20son%20acreditaciones,que%20ver%20con%20su%20identidad.), sin verse obligados a solicitar autorización de una autoridad intermediaria o centralizada y les da control sobre cómo se comparten y usan sus datos personales.

Un SSI puede ser una identidad descentralizada, pero también podría consistir de [datos](https://es.wikipedia.org/wiki/Datos) de una cuenta de redes sociales, un historial de transacciones en un sitio de comercio electrónico o la certificación de amigos o colegas.

Acá dejamos varios trabajos en esta linea:
- [Identidad digital auto-soberana - Proyecto DIDI](https://didi.org.ar/aidi-identidad-digital-auto-soberana/)
- [Identidad digital auto-gestionada: El futuro de la identidad digital: Auto-gestión, billeteras digitales y blockchain](https://publications.iadb.org/es/identidad-digital-auto-gestionada-el-futuro-de-la-identidad-digital-auto-gestion-billeteras)
- [Identidad Digital Auto-Soberana, centrada en el ciudadano](https://www.otdec.org/2021/03/23/identidad-digital-auto-soberana-centrada-en-el-ciudadano/)
