### ISSUE TITLE
Otras proyectos para analizar y considerar agregarlos

### ISSUE THREAD

**Issue by rodolfomiranda** [gcba/Identidad-digital#5]
Paso una lista de proyectos que tienen relevancia en el mundo SSI para analizar y ver si vale la pena incluir en la sección 3  "Trabajos Preexistentes":

- [Pan-Canadian Trust Framework Overview](https://diacc.ca/wp-content/uploads/2016/08/PCTF-Overview-FINAL.pdf). Es parte de [Digital Identification and Authentication Council of Canada](https://diacc.ca)

- Institute of International Finance (IIF) [Global Assured Identity Network White Paper](https://www.iif.com/Publications/ID/4573/Global-Assured-Identity-Network-White-Paper)

- [The UK digital identity and attributes trust framework](https://www.gov.uk/government/publications/the-uk-digital-identity-and-attributes-trust-framework/the-uk-digital-identity-and-attributes-trust-framework)

- [Global Legal Entity Identifier Foundation](https://www.gleif.org) (GLEIF): esta implementación esta basada en KERI

- [YOMA](https://www.yoma.foundation): Yoma is a youth marketplace that is incubated by UNICEF in Africa.  It enables youth to Learn (through Yoma learning partners), Earn (through employers in the ecosystem) and Thrive by completing Impact challenges (e.g., plastic clean-up, reforestation) that benefit our environment and communities.  All of this is enabled through a SSI-enabled digital CV and personalized learning environment. [ToIP Task Force](https://wiki.trustoverip.org/display/HOME/YOMA+Ecosystem+Task+Force)

- [Good Health Pass](https://www.goodhealthpass.org/blueprint)

- [Wyoming Legislation for DAOs](https://www.wyoleg.gov/Legislation/2021/SF0038)

**Comment by dtrejopizzo** [comment]
Incorporados.
