### ISSUE TITLE
Adicional sobre did:peer

### ISSUE THREAD

**Issue by rodolfomiranda** [gcba/Identidad-digital#7]
Un dato adicional que creo que vale la pena agregar es que por lo general toda comunicación es entre dos partes, entonces es ahi donde siempre se utiliza did:peer. Una vez establecida esa confianza, el canal (didcomm, v2) queda abierto para siempre y es 100% seguro para las dos partes. Ese canal es el que luego se utiliza para interactuar y pasarse credenciales y pruebas que están atados a otros did. DIDPeer soporta key rotation, con lo cual el canal es en principio de por vida, una vez que estableciste la confianza con alguien y se compartieron los did peer, ya puede comunicarse de forma segura sin intermediarios.

Luego lo redacto para poder agregarlo al main doc.

**Comment by dtrejopizzo** [comment]
Perfecto, aguardamos el texto para actualizarlo en el paper!

**Comment by dtrejopizzo** [comment]
Aguardamos redacción para sumar, pero mientras tanto incorporamos esto al documento.
